export const REQUEST_STARTED = 'REQUEST_STARTED';
export const REQUEST_ERRORED = 'REQUEST_ERRORED';
export const REQUEST_SUCCEED = 'REQUEST_SUCCEED';

export const MAIN_BUTTON_PRESSED = 'MAIN_BUTTON_PRESSED';
export const CANCEL_BUTTON_PRESSED = 'CANCEL_BUTTON_PRESSED';
